package cli

import (
	"bytes"
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stretchr/testify/require"
	stripesdk "github.com/stripe/stripe-go/v82"

	"github.com/EduardMaghakyan/gatr-cli/pkg/schema"
	gstripe "github.com/EduardMaghakyan/gatr-cli/pkg/stripe"
)

// These tests exercise runImport's pre-network guards (flag validation,
// file-refuse) and the pure renderer. Full end-to-end (real Stripe) is
// covered by TestScenario_ImportRoundTrip in scenario_test.go.

func TestRunImport_RequiresProjectSlug(t *testing.T) {
	var out, errOut bytes.Buffer
	err := runImport(context.Background(), &out, &errOut, &importOptions{})
	require.Error(t, err)
	require.Contains(t, err.Error(), "--project")
	require.Contains(t, errOut.String(), "--project")
}

func TestRunImport_RejectsBadSlug(t *testing.T) {
	var out, errOut bytes.Buffer
	err := runImport(context.Background(), &out, &errOut, &importOptions{
		projectSlug: "bad name!", // space + ! — invalid
	})
	require.Error(t, err)
	require.Contains(t, err.Error(), "may only contain")
}

func TestRunImport_RefusesExistingFile(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "gatr.yaml")
	require.NoError(t, os.WriteFile(path, []byte("preexisting"), 0o600))

	var out, errOut bytes.Buffer
	err := runImport(context.Background(), &out, &errOut, &importOptions{
		configPath:  path,
		projectSlug: "demo",
	})
	require.Error(t, err)
	require.Contains(t, err.Error(), "refuse to overwrite")
	// No Stripe call happened → env vars and bad keys don't matter.
}

// ---- renderer tests (pure) -----------------------------------------

func TestRenderImportedYAML_HeaderAndBody(t *testing.T) {
	// Build a minimal ImportResult by hand — no Stripe round-trip.
	result := gstripe.ImportResult{
		Config: schema.Config{
			Version:       4,
			Project:       "demo",
			Features:      []schema.Feature{},
			Limits:        []schema.Limit{},
			Credits:       []schema.Credit{},
			Operations:    []schema.Operation{},
			MeteredPrices: []schema.MeteredPrice{},
			Plans: []schema.Plan{
				{
					ID:       "pro",
					Name:     "Pro",
					Features: []string{},
					Limits:   map[string]schema.NumberOrUnlimited{},
					Grants:   map[string]schema.NumberOrUnlimited{},
					Includes: map[string]schema.NumberOrUnlimited{},
				},
			},
		},
		Notes: []gstripe.ImportNote{
			{Kind: gstripe.NoteSkipped, Subject: "price_xyz", Reason: "one-time price"},
		},
	}
	body, err := renderImportedYAML(result, 1, 1, 0)
	require.NoError(t, err)
	s := string(body)

	// Header shape
	require.True(t, strings.HasPrefix(s, "# Generated by `gatr import`"),
		"output must open with a header comment")
	require.Contains(t, s, "1 products, 1 prices, 0 meters")
	require.Contains(t, s, "1 plans, 0 metered prices")
	require.Contains(t, s, "[skipped] price_xyz: one-time price")
	require.Contains(t, s, "gatr validate")
	require.Contains(t, s, "gatr push --dry-run")

	// Yaml body shape — must be valid yaml of the expected shape.
	require.Contains(t, s, "version: 4")
	require.Contains(t, s, "project: demo")
	require.Contains(t, s, "id: pro")
}

// TestRenderImportedYAML_RoundTripsViaSchema is the contract test
// that holds everything together: whatever yaml we emit MUST parse
// cleanly via the same schema validator that `gatr validate` uses.
// This is the invariant that justifies the "run gatr validate next"
// hint in the success message.
func TestRenderImportedYAML_RoundTripsViaSchema(t *testing.T) {
	// Build a result with a plan + metered price + some notes.
	result := gstripe.TranslateFromStripe(
		"demo",
		[]*stripesdk.Product{
			{ID: "prod_A", Name: "Pro", Active: true},
		},
		[]*stripesdk.Price{
			{
				ID: "price_m", Active: true, Currency: "usd",
				BillingScheme: stripesdk.PriceBillingSchemePerUnit,
				UnitAmount:    2900,
				Product:       &stripesdk.Product{ID: "prod_A"},
				Type:          stripesdk.PriceTypeRecurring,
				Recurring: &stripesdk.PriceRecurring{
					Interval: "month", IntervalCount: 1, UsageType: "licensed",
				},
			},
		},
		nil,
	)

	body, err := renderImportedYAML(result, 1, 1, 0)
	require.NoError(t, err)

	// Write to a tempfile and re-parse via the canonical validator.
	dir := t.TempDir()
	path := filepath.Join(dir, "roundtrip.yaml")
	require.NoError(t, os.WriteFile(path, body, 0o600))

	_, err = schema.ParseFileAndValidate(path)
	require.NoError(t, err, "emitted yaml must pass schema validation — this is the import contract")
}
