package cli

import (
	"context"
	"fmt"
	"io"
	"os"
	"strings"
	"time"

	"github.com/spf13/cobra"
	"sigs.k8s.io/yaml"

	gstripe "github.com/EduardMaghakyan/gatr-cli/pkg/stripe"
)

// importOptions collects every tunable flag `gatr import` exposes.
// Mirrors pushOptions/validateOptions shape so flag precedence +
// Stripe credentials behave identically across the three commands.
type importOptions struct {
	configPath  string // output path for the generated yaml
	projectSlug string
	secretKey   string
	credFile    string
	force       bool
}

func newImportCmd() *cobra.Command {
	opts := &importOptions{}
	cmd := &cobra.Command{
		Use:   "import",
		Short: "Read an existing Stripe account and emit a starter gatr.yaml",
		Long: `gatr import — reverse of ` + "`gatr push`" + `.

Reads every active product / price / meter on the bound Stripe account
and writes a starter gatr.yaml the operator can then iterate on. The
generated file is always schema-valid; features / limits / credits
blocks come back empty because Stripe has no equivalent — fill them in
by hand.

Refuses to overwrite an existing file unless --force is set. Archived
and unsupported items (one-time prices, tiered prices, intervals other
than monthly/yearly) are skipped and listed in a header comment.`,
		RunE: func(cmd *cobra.Command, _ []string) error {
			return runImport(cmd.Context(), cmd.OutOrStdout(), cmd.ErrOrStderr(), opts)
		},
	}
	cmd.Flags().StringVarP(&opts.configPath, "config", "c", "gatr.yaml", "Output path for the generated yaml")
	cmd.Flags().StringVar(&opts.projectSlug, "project", "", "Project slug — used as the `project:` field in the generated yaml (required)")
	cmd.Flags().StringVar(&opts.secretKey, "key", "", "Stripe secret key (defaults to $STRIPE_SECRET_KEY or ~/.gatr/credentials.toml)")
	cmd.Flags().StringVar(&opts.credFile, "credentials", "", "Override ~/.gatr/credentials.toml path")
	cmd.Flags().BoolVar(&opts.force, "force", false, "Overwrite the output file if it already exists")
	return cmd
}

func runImport(ctx context.Context, out, errOut io.Writer, opts *importOptions) error {
	if opts.projectSlug == "" {
		printErr(errOut, "--project is required")
		return fmt.Errorf("--project is required")
	}
	if err := validateProject(opts.projectSlug); err != nil {
		printErr(errOut, err.Error())
		return err
	}
	if _, err := os.Stat(opts.configPath); err == nil && !opts.force {
		msg := fmt.Sprintf("refuse to overwrite existing %s (pass --force)", opts.configPath)
		printErr(errOut, msg)
		return fmt.Errorf("%s", msg)
	}

	client, err := gstripe.NewClient(gstripe.ClientOptions{
		SecretKey:      opts.secretKey,
		CredentialFile: opts.credFile,
		ProjectID:      opts.projectSlug, // cosmetic — ListAll* doesn't consult it
	})
	if err != nil {
		printErr(errOut, err.Error())
		return err
	}

	products, err := client.ListAllProducts(ctx)
	if err != nil {
		printErr(errOut, err.Error())
		return err
	}
	prices, err := client.ListAllPrices(ctx)
	if err != nil {
		printErr(errOut, err.Error())
		return err
	}
	meters, err := client.ListAllMeters(ctx)
	if err != nil {
		printErr(errOut, err.Error())
		return err
	}

	result := gstripe.TranslateFromStripe(opts.projectSlug, products, prices, meters)
	body, err := renderImportedYAML(result, len(products), len(prices), len(meters))
	if err != nil {
		printErr(errOut, err.Error())
		return err
	}
	if err := os.WriteFile(opts.configPath, body, 0o600); err != nil {
		printErr(errOut, err.Error())
		return err
	}

	printImportSummary(out, opts.configPath, result)
	return nil
}

// renderImportedYAML marshals the Config to yaml and prepends a header
// comment listing what was imported + what was skipped. sigs.k8s.io/yaml
// is the canonical JSON-tag-aware yaml lib in this repo (pkg/schema
// uses it for parsing); reusing it here means the output's field order
// matches the parser's expectations.
func renderImportedYAML(result gstripe.ImportResult, nProducts, nPrices, nMeters int) ([]byte, error) {
	body, err := yaml.Marshal(&result.Config)
	if err != nil {
		return nil, fmt.Errorf("marshal yaml: %w", err)
	}
	header := buildImportHeader(result, nProducts, nPrices, nMeters)
	return append([]byte(header), body...), nil
}

// buildImportHeader is the comment block that opens every imported
// yaml. Kept as a pure-string function so tests can assert on shape
// without file IO.
//
// Layout:
//
//	# Generated by `gatr import` on <date>.
//	# Source: <N> products, <N> prices, <N> meters scanned.
//	# Imported: <M> plans, <M> metered prices.
//	# Notes: (one line per entry) — skip reasons, per-seat hints, collisions.
//	# Next steps: validate / review / push --dry-run.
func buildImportHeader(result gstripe.ImportResult, nProducts, nPrices, nMeters int) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# Generated by `gatr import` on %s.\n", time.Now().UTC().Format("2006-01-02"))
	fmt.Fprintf(&b, "# Source: %d products, %d prices, %d meters on Stripe.\n",
		nProducts, nPrices, nMeters)
	fmt.Fprintf(&b, "# Imported: %d plans, %d metered prices.\n",
		len(result.Config.Plans), len(result.Config.MeteredPrices))

	if len(result.Notes) > 0 {
		b.WriteString("#\n# Notes:\n")
		for _, n := range result.Notes {
			fmt.Fprintf(&b, "#   - [%s] %s: %s\n", n.Kind, n.Subject, n.Reason)
		}
	}

	b.WriteString("#\n# Next steps:\n")
	b.WriteString("#   - Fill in the empty `features:`, `limits:`, `credits:`, `operations:` blocks.\n")
	b.WriteString("#     These are gatr concepts that Stripe doesn't model, so they're empty.\n")
	b.WriteString("#   - Run `gatr validate` to confirm the file parses.\n")
	b.WriteString("#   - Run `gatr push --dry-run` — it should report no changes (round-trip).\n")
	b.WriteString("#\n")
	return b.String()
}

// printImportSummary echoes the outcome to stdout — mirroring the
// final green-line render of push/validate so operators get the same
// shape across all three commands.
func printImportSummary(out io.Writer, path string, result gstripe.ImportResult) {
	skipped := 0
	for _, n := range result.Notes {
		if n.Kind == gstripe.NoteSkipped || n.Kind == gstripe.NoteArchivedSkip {
			skipped++
		}
	}
	fmt.Fprintln(out, successStyle.Render(fmt.Sprintf(
		"✓ Wrote %s (%d plans, %d metered prices).",
		path, len(result.Config.Plans), len(result.Config.MeteredPrices),
	)))
	if skipped > 0 {
		fmt.Fprintln(out, subtleStyle.Render(fmt.Sprintf(
			"  %d item(s) skipped — see the header comment in %s.", skipped, path,
		)))
	}
	fmt.Fprintln(out)
	fmt.Fprintln(out, subtleStyle.Render("  Next:"))
	fmt.Fprintln(out, "  "+codeStyle.Render("gatr validate -c "+path)+subtleStyle.Render("           # confirm the file parses"))
	fmt.Fprintln(out, "  "+codeStyle.Render("gatr push -c "+path+" --dry-run")+subtleStyle.Render("  # round-trip check (expect: no changes)"))
}
