// Package typegen renders typed bindings from a parsed gatr.yaml.
package typegen

import (
	"fmt"
	"sort"
	"strings"

	schema "github.com/EduardMaghakyan/gatr-cli/pkg/schema"
)

// RenderTypeScript produces a module-augmentation file that narrows
// @gatr/node's id types to the literals in cfg.
func RenderTypeScript(cfg *schema.Config) (string, error) {
	var sb strings.Builder

	sb.WriteString("// Code generated by `gatr typegen`. DO NOT EDIT.\n")
	sb.WriteString("// Re-run after editing gatr.yaml.\n")
	sb.WriteString(fmt.Sprintf("// project: %s, schema version: %d\n\n", cfg.Project, cfg.Version))
	sb.WriteString(`declare module "@gatr/node" {`)
	sb.WriteString("\n")

	writeMap(&sb, "GatrFeatureMap", featureIDs(cfg))
	writeMap(&sb, "GatrLimitMap", limitIDs(cfg))
	writeMap(&sb, "GatrCreditMap", creditIDs(cfg))
	writeMap(&sb, "GatrOperationMap", operationIDs(cfg))
	writeMap(&sb, "GatrMeteredPriceMap", meteredPriceIDs(cfg))
	writeMap(&sb, "GatrPlanMap", planIDs(cfg))

	sb.WriteString("}\n\nexport {};\n")
	return sb.String(), nil
}

func writeMap(sb *strings.Builder, name string, ids []string) {
	sb.WriteString(fmt.Sprintf("  interface %s {\n", name))
	sort.Strings(ids)
	for _, id := range ids {
		sb.WriteString(fmt.Sprintf("    %s: true;\n", quoteKey(id)))
	}
	sb.WriteString("  }\n\n")
}

// quoteKey wraps the id in quotes when it isn't a valid JS identifier.
func quoteKey(id string) string {
	if isValidIdent(id) {
		return id
	}
	return fmt.Sprintf("%q", id)
}

func isValidIdent(s string) bool {
	if s == "" {
		return false
	}
	for i, r := range s {
		first := i == 0
		switch {
		case first && (r == '_' || r == '$' || (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z')):
			continue
		case !first && (r == '_' || r == '$' || (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9')):
			continue
		default:
			return false
		}
	}
	return true
}

func featureIDs(cfg *schema.Config) []string {
	out := make([]string, 0, len(cfg.Features))
	for _, f := range cfg.Features {
		out = append(out, f.ID)
	}
	return out
}
func limitIDs(cfg *schema.Config) []string {
	out := make([]string, 0, len(cfg.Limits))
	for _, x := range cfg.Limits {
		out = append(out, x.ID)
	}
	return out
}
func creditIDs(cfg *schema.Config) []string {
	out := make([]string, 0, len(cfg.Credits))
	for _, x := range cfg.Credits {
		out = append(out, x.ID)
	}
	return out
}
func operationIDs(cfg *schema.Config) []string {
	out := make([]string, 0, len(cfg.Operations))
	for _, x := range cfg.Operations {
		out = append(out, x.ID)
	}
	return out
}
func meteredPriceIDs(cfg *schema.Config) []string {
	out := make([]string, 0, len(cfg.MeteredPrices))
	for _, x := range cfg.MeteredPrices {
		out = append(out, x.ID)
	}
	return out
}
func planIDs(cfg *schema.Config) []string {
	out := make([]string, 0, len(cfg.Plans))
	for _, x := range cfg.Plans {
		out = append(out, x.ID)
	}
	return out
}
